name: Node.js CI/CD

on:
  push:
    branches:
      - master  # Change to your project's main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20  # Change to your preferred Node.js version

    # - name: Install Dependencies
    #   run: npm install

    - name: Run Tests
      run: node app.js  # Replace with your actual test command

